import { coerce, object, string } from "zod";

export const envSchema = object({
    PORT: string().transform((val) => parseInt(val, 10)),
    MYREKAP_URL: string(),
    MYFLOWER_URL: string(),
    DATABASE_URL: string(),
    JWT_ACCESS: string().min(20),
    JWT_RESET_PASSWORD: string().min(20),
    SUPERADMIN_FULL_NAME: string(),
    SUPERADMIN_USERNAME: string().max(15),
    SUPERADMIN_EMAIL: string().email(),
    SUPERADMIN_PHONE_NUMBER: string().min(10),
    SUPERADMIN_PASSWORD: string().min(5),
    CLOUDINARY_CLOUD_NAME: string(),
    CLOUDINARY_API_KEY: string(),
    CLOUDINARY_API_SECRET: string(),
    MIDTRANS_CLIENT_KEY: string(),
    MIDTRANS_SERVER_KEY: string(),
    BREVO_API_KEY: string(),
    BREVO_SENDER_NAME: string(),
    BREVO_SENDER_EMAIL: string(),
    BREVO_TEMPLATE_OTP_ID: coerce.number(),
    BREVO_TEMPLATE_ORDER_OWNER_ID: coerce.number(),
    MANAGER_EMAIL: string().email(),
});
